### ISSUE TITLE
formatting error in search results page

### ISSUE THREAD

**Issue by andrewsu** [SuLab/outbreak.info#109]
I don't see this commonly, but just noticed it here https://outbreak.info/resources?search=ace2%20AND%20hypertension&filter=%40type%3Aclinicaltrial&page=0&size=10&sort=-datePublished

![image](https://user-images.githubusercontent.com/2635409/82350888-bf3d9780-99b0-11ea-85b4-eb7f1fa09b18.png)

**Comment by netham91** [comment]
This issue is because of the "________________" part in the right hand description of the part which is breaking. As soon as you remove that, this issue disappears as seen in the second pic and then the whole page formatting changes as seen in the first pic.
![Screenshot 2020-05-27 at 8 32 22 PM](https://user-images.githubusercontent.com/6914498/83037486-74c7b500-a059-11ea-98dd-7eee95c042e9.png)


![Screenshot 2020-05-27 at 8 32 36 PM](https://user-images.githubusercontent.com/6914498/83037406-5f528b00-a059-11ea-823a-9bad58df450b.png)

**Comment by flaneuse** [comment]
thanks @netham91 !
