### ISSUE TITLE
Fix metadata embed

### ISSUE THREAD

**Issue by flaneuse** [SuLab/outbreak.info#115]
e.g. outbreak.info/resources/NCT04283461

```
vue-meta.esm.js?58ca:690 Uncaught TypeError: val.replace is not a function
    at eval (vue-meta.esm.js?58ca:690)
```

related to either vue-meta not replacing initial `null` value and/or async issue

**Comment by netham91** [comment]
I investigated this issue. The issue is because in the call made in the API for the resource
https://api.outbreak.info/resources/query?q=_id:%22NCT04283461%22&size=1
in the returned data, the value of phaseNumber is a number type which cause val.replace to fail.

I checked it across other resources also and it's the same issue.

**Comment by flaneuse** [comment]
Thanks @netham91 very helpful! Fixed in https://github.com/SuLab/outbreak.info/commit/2fe76a877898cc4694935986fbbbf3e807008379

**Comment by flaneuse** [comment]
Update: `[null]` causes problems.  Should be [] or null.
