### ISSUE TITLE
Missing Data for Jun 1-11, or 0 Daily New Deaths [San Diego County, but may apply elsewhere]?

### ISSUE THREAD

**Issue by sabahzero** [SuLab/outbreak.info#140]
There are 0 'daily new deaths' for San Diego County from Jun 1-11
Is the data for these numbers absent, or are the numbers in truth 0 for these dates?
If the former, recommendation to not have a line drawn between that gap for accuracy in data visualization.
It may be worth exploring if this also applies to other locations?
<img width="1126" alt="SD" src="https://user-images.githubusercontent.com/16907482/86200125-c0fe8d00-bb10-11ea-800f-9b43903ebd16.png">

**Comment by flaneuse** [comment]
Thanks @sabahzero. I just double checked the [NYT's data](https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv), and yes, San Diego had no increases in death from 31 May - 11 June.  Whether that's accurate is another issue.

There should be a line drawn between the data points, since it's a seven day rolling average, and 0 is a real number.  So, for instance, the data from 31 May should be the average of that day (0) + the 3 previous days (7, 10, 5) + the 3 subsequent days (0,0,0) = 3.14.

**Comment by sabahzero** [comment]
Thanks for the clarification and explanation! Agree, if the real number is 0 it makes sense to have a line drawn across. 

Certainly interesting on that number.
